export enum GALLERY_ACTIONS_TYPES {
  SET_CATEGORY_PHOTO = 'categoryReducer/SET_CATEGORY_PHOTO',
  SET_ALL_GALLERY_PHOTO = 'categoryReducer/SET_ALL_GALLERY_PHOTO',
  SET_SELECTED_PHOTO = 'categoryReducer/SET_SELECTED_PHOTO',
  GET_CATEGORY_DATA = 'categoryReducer/GET_CATEGORY_DATA',
  GET_PHOTO = 'categoryReducer/GET_PHOTO',
}
